### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Tanmay-Nalawade** [INFO-526-F24/project-01-Vizzards#4]
---
name: Vizcats
about: Peer review of project proposal
title: Proposal peer review
labels: ''
assignees: ''
---

The following is the peer review of the project proposal by "Vizcats". The team members that participated in this review are 

- Sreeharsha Nalluri - @SreeharshaNalluri
- Jay Patil - @jayast29
- Tanmay Nalawade - @Tanmay-Nalawade
- Pragnya Narasimha - @ praagnya08

- Describe the goal of the project.
    The project aims to analyze and visualize different types of network attacks within IoT environments. In order to provide insights into the unique behaviors of network traffic under diverse attack situations, the study will examine how different attacks affect network properties like as protocol usage, bandwidth, and inter-arrival periods using the RT-IoT 2022 dataset. In order to improve cybersecurity in IoT systems, this analysis will assist in identifying trends that may guide future intrusion detection tactics that are more successful.

- Describe the data used or collected.
    This project uses the RT-IoT 2022 dataset, which comprises 77 columns and 123,117 rows of network traffic data. Protocol and service details, packet counts, flow properties, attack kinds, and payload details are important elements. In order to create a reliable dataset appropriate for cybersecurity research in IoT contexts, data was collected using actual IoT devices and attack scenarios were simulated to capture both normal and malicious traffic.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
    The research questions will be addressed by analyzing specific variables associated with different types of attacks:
    Question 1 will compare attack and normal traffic scenarios by analyzing the protocol, service, and port numbers (variables proto, service, and id.resp_p).• For 
    Question 2, Differences between attacks will be examined in the payload behavior (fwd_pkts_payload.avg), inter-arrival time (fwd_iat.min, flow_iat.min), and bandwidth (fwd_pkts_tot, bwd_pkts_tot).The contribution of various network dimensions (protocol, bandwidth, inter-arrival time, etc.) to attack patterns will be ascertained by dimensional analysis. 
For 
    Question 3.
To find patterns unique to an attack, this method will make use of statistical comparisons and visualizations.

- Is there anything that is unclear from the proposal?
    The proposal is mostly clear. However, more information about the precise visualisation and analysis methods that will be used, such as particular charts or machine learning models, may offer a clearer picture of how the initiative will draw attention to attack patterns.

- Provide constructive feedback on how the team might be able to improve their project.
    The team could consider providing a flowchart or diagram showing the analysis pipeline, from data cleaning to visualization and interpretation. Furthermore, the methodology would be more thorough if it made clear which particular statistical methods or algorithms such as clustering or anomaly detection might be used.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
    It may be especially instructive to examine the behaviors of bandwidth, payload, and inter-arrival time during attacks. Observing how these dimensions alter in response to various attack kinds would give the presentation a potent visual and analytical element. Highlighting particular trends for common attack types, such as DDoS and SSH brute-force attacks, would be intriguing.

- Provide constructive feedback on any issues with file and/or code organization.
    Organizing the code into modular scripts, such as distinct scripts for data cleaning, feature engineering, and analysis, would aid in improving reproducibility. To make the project easier for anyone who wants to duplicate or understand the workflow, a README with detailed instructions on how to run each script and its dependencies can be included.

- (Optional) Any further comments or feedback?
    The goal of this project is to improve IoT cybersecurity through the analysis of network data attack patterns. The method of looking at payload, protocol, and bandwidth characteristics throughout various attacks is perceptive and should yield useful results.

    Feedback: Consider adding a few early visualizations of attack patterns to showcase initial insights, and possibly explore a machine-learning model for detecting patterns automatically. Great work on a timely topic!

**Comment by Ash-Y-28** [comment]
We've taken your feedback into account and have actively worked on improving our proposal based on your suggestions. Thank you for providing such detailed and helpful insights. We're committed to refining our project and appreciate your support. Thanks again!
