### ISSUE TITLE
Update website ASAP

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-F24/project-01-Vizzards#5]
Greetings @INFO-526-F24/vizzards, 

I cannot see your full report on your website, but I can see that it was written in your `index.qmd`, see [LINK](https://info-526-f24.github.io/project-01-Vizzards/). Please update your website ASAP so that I can grade the write up.

**Comment by Ash-Y-28** [comment]
Thank you for the feedback, Professor. The issue has been resolved, and the index.qmd should now render correctly. We appreciate your guidance!

**Comment by Gchism94** [comment]
The website should render correctly, but the website it not updated.

**Comment by Ash-Y-28** [comment]
Issue resolved.
