### ISSUE TITLE
Write-up feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-F24/project-01-Vizzards#8]
Dear @INFO-526-F24/vizzards: Below is the score breakdown for your write-up. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

## Write-up

Category | Available | Earned | Feedback
-- | -- | -- | --
Introduction/Data | 6 | 6 | The introduction provides a concise and engaging overview of the project goals and questions. The dataset is described clearly, including its source and preprocessing steps. The context provided ensures the reader understands the scope of the analysis. This section is well-executed.
Methodology | 10 | 9 | The methodology is well-structured and provides sufficient detail to follow the analytical process. The chosen methods are appropriate for addressing the research questions. A minor area for improvement is to justify the methods more explicitly, explaining why these approaches were chosen over alternatives and highlighting any assumptions or limitations.
Results | 14 | 13.5 | The results are clearly presented and supported by strong visualizations. Most visualizations are intuitive and effectively communicate key findings. A few figures could benefit from additional annotations or improved axis labeling to highlight insights more explicitly.
Discussion | 6 | 5.5 | The discussion ties the findings back to the research questions and provides reasonable interpretations. However, it could be strengthened by addressing limitations, discussing broader implications of the results, and suggesting areas for future research or application.
Organization + Formatting | 4 | 4 | The report is professionally formatted, with logical structure and clear writing. Figures are well-placed, and the overall presentation is polished and easy to follow. There are no noticeable formatting issues.
Total | 40 | 38 | This report is very strong, with clear organization, well-executed methodology, and effective visualizations. Minor refinements in justification, visualization detail, and critical discussion would bring it to an exemplary level.

<hr>
<h3><strong>General Feedback</strong></h3>
<ul>
<li>
<p><strong>Strengths</strong>:</p>
<ul>
<li>The introduction and data section are clear and engaging.</li>
<li>The methodology is well-documented and logical.</li>
<li>Visualizations are well-crafted and support the narrative effectively.</li>
<li>The report is polished and professional, with excellent organization.</li>
</ul>
</li>
<li>
<p><strong>Opportunities for Improvement</strong>:</p>
<ol>
<li><strong>Methodology</strong>: Provide more justification for the choice of methods, referencing relevant studies or alternative approaches. Briefly discuss any assumptions or limitations in the analysis.</li>
<li><strong>Results</strong>: Add more detailed annotations or labels to certain visualizations to improve clarity. Include additional statistical summaries or contextual insights for a deeper understanding.</li>
<li><strong>Discussion</strong>: Expand on the limitations and implications of the findings, and suggest future research directions or applications for the work.</li>
</ol>
</li>
</ul>
<p>This report demonstrates excellent effort, strong technical execution, and professional presentation. With minor adjustments, it could reach near-perfect marks.</p></body></html>

**Comment by Ash-Y-28** [comment]
Thanks for the feedback!!
